configured_endpoints: 19
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/irrigation-solutions-software-development/init_omega.py-1b284c11ebcccc1646b579595c39ecba4fa75500df895ec9fbaa1e839a1d84a3.yml
openapi_spec_hash: 356a7298b2abac3fdf72ad5ee046b952
config_hash: 14e8ec9faaff1529ae82a83fb1e36e6a
