configured_endpoints: 19
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/irrigation-solutions-software-development/init_omega.py-7cf470f91aceda69ade800fe3a7d51664d9ec20bb174b426f0d558f3687d4a7a.yml
openapi_spec_hash: 356a7298b2abac3fdf72ad5ee046b952
config_hash: 5cda3a0330e2206a48900018de76ea50
